version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:7.16.1
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Монтирование скриптов
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных
    restart: always
  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    build: ./
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  esdata:
  redis_data:
  postgres_data:




