spring:
  application:
    name: 'TestTask'
  jpa:
    hibernate:
      ddl-auto: 'update'
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    database: postgresql
  config:
    import: 'optional:file:.env[.properties]'
  datasource:
    url: 'jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}'
    driver-class-name: 'org.postgresql.Driver'
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: 'w4vF3xKpQk6YbT9mLzN2R7sAqCtUeXjHnD8GyJfPw0ZV5rI1oBhWu4MdLcSgOxEi'
  expiration: '3600000'