create table if not exists users
(
    id            bigint not null
        primary key,
    date_of_birth date,
    name          varchar(500),
    password      varchar(500)
);
create table if not exists account
(
    id              bigint not null
        primary key,
    balance         numeric(38, 2),
    initial_balance numeric(38, 2),
    user_id         bigint
        constraint ukh6dr47em6vg85yuwt4e2roca4
            unique
        constraint fkra7xoi9wtlcq07tmoxxe5jrh4
            references users
);
create table if not exists email_data
(
    id      bigint generated by default as identity
        primary key,
    email   varchar(200)
        constraint uknwt9u3p3dlhfekcxxh96j8x8o
            unique,
    user_id bigint
        constraint fk62aitajoe5fk8s6a7b0830qjd
            references users
);
create table if not exists phone_data
(
    id      bigint generated by default as identity
        primary key,
    phone   varchar(13)
        constraint ukosdf5rk1hhd70y73s7aa2wafo
            unique,
    user_id bigint
        constraint fkddj6vjnjncixxkhhjee7dyc2h
            references users
);
